name: Python Linting on Changed Files

on: push

jobs:
  lint-changed-files:
    name: Lint Changed Python Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Get list of changed Python files
        id: get-changed-files
        run: |
          files=$(git diff --name-only $(git merge-base HEAD origin/main) HEAD | grep '\.py$')
          echo "Changed files: $files"
          echo "::set-output name=files::$files"

      - name: Lint changed Python files
        run: |
          files="${{ steps.get-changed-files.outputs.files }}"
          if [[ -n "$files" ]]; then
            flake8 $files
          else
            echo "No Python files were changed."
          fi
